# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod
mod_version=1.0.0+26.1.2
maven_group=com.example.votebridge
archives_base_name=votebridge

# Minecraft / Fabric
minecraft_version=26.1.2
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Dependencies
fabric_api_version=0.150.0+26.1.2

# PB4 Placeholder API
pb4_placeholder_api_version=3.0.0+26.1

# Java toolchain
java_version=25